spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soompyo?serverTimezone=Asia/Seoul
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
app:
  jwt:
    secret: dlrjtdmsdlqdptjsksmsthflrkdkslsrjtdldu
    access-exp-minutes: 30